baseURL = 'https://aifoc.us/'
languageCode = 'en-us'
title = 'AI Focus'
theme = 'aifocustheme'

[params]
  about = "Hello, I'm [Paul Kinlan](https://paul.kinlan.me/), a Developer Advocate on Chrome and a Web Developer. There's a significant shift in the industry driven by AI, and I'm developing an opinion through a collection of essays and projects on how AI is changing the medium of the web and web development at large."
  defaultAuthor = "paulkinlan"
  images = ['/images/card.jpeg']
[params.authors]
[params.authors.paulkinlan]
  name = "Paul Kinlan"
  homepage = "https://paul.kinlan.me/"
[params.authors.andreban]
  name = "Andre Cipriani Bandarra"
  homepage = "https://bandarra.me/"

[taxonomies]
  author = 'authors'
  post = 'posts'

[permalinks.page]
    posts = '/:slug/'
    tutorials = '/training/:slug/'